spring:
  redis:
    common:
      host: localhost
      port: 6379
      password: redispasswd
      timeout: 30000
    order:
      host: localhost
      port: 6379
      password: redispasswd
      timeout: 30000
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hy-main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: password123
      hikari:
        # 池中最大连接数，包括闲置和使用中的连接
        maximum-pool-size: 200
        # 最小空闲连接数
        minimum-idle: 20
        # 连接池用完后，申请新连接的等待时间，超出此时间则抛出异常
        connection-timeout: 30000
    order:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/hy-order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: password123
      hikari:
        # 池中最大连接数，包括闲置和使用中的连接
        maximum-pool-size: 200
        # 最小空闲连接数
        minimum-idle: 20
        # 连接池用完后，申请新连接的等待时间，超出此时间则抛出异常
        connection-timeout: 30000

mybatis:
  mapperScan:
    basePackages:
      main: com.wenxiahy.hy.order.mapper.main
      order: com.wenxiahy.hy.order.mapper.order
